### ISSUE TITLE
Dependant Package "defaults-deep" is flagged as having a 'moderate' issue

### ISSUE THREAD

**Issue by NorthernMan54** [jonschlinkert/defaults-deep#6] opened 2019-02-12 14:25 UTC
Prior to publishing one of my applications today, ran into this warning today.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ defaults-deep                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ update                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ update > base-cli-process > base-config-process >            │
│               │ base-config-schema > base-pkg > expand-pkg > defaults-deep   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/778                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by jonschlinkert** [comment] 2019-02-14 18:25
duplicate of https://github.com/jonschlinkert/defaults-deep/pull/5

**Closed as completed by jonschlinkert** 2019-02-14 18:25 UTC
